name: Test

on: push

jobs:
  run:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_extensions: js,vue,ts

      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2
        with:
          jestArgs: test/unit

      # - name: Build project
      #   run: yarn build

      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn start
          record: true
          command-prefix: 'percy exec -- npx'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
